Controllers/AgentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyEticketApplication.Data;
using MyEticketApplication.Models;
using System.Net;

namespace MyEticketApplication.Controllers
{
    public class AgentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;
        public AgentController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _context.Agents.ToListAsync();
            return View(data);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var agent = await _context.Agents
            .FirstOrDefaultAsync(m => m.AgentId == id);
            return View(agent);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Agent agent)
        {
            if (agent.ImageUrl != null)
            {
                agent.UrlImage = ProcessUploadImage(agent);

                _context.Agents.Add(agent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            };
            return View(agent);
        }
        public string ProcessUploadImage(Agent agent)
        {
            string uniqueFileName = null;
            if (agent.ImageUrl != null)
            {

                string uploadsFolder = Path.Combine(_environment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + agent.ImageUrl.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    agent.ImageUrl.CopyTo(fileStream);
                };
            }
            return uniqueFileName;
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var agent = await _context.Agents
            .FirstOrDefaultAsync(m => m.AgentId == id);
            return View(agent);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id != 0)
            {
                var agent = await _context.Agents
               .FirstOrDefaultAsync(m => m.AgentId == id);

                var CurrentImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", agent.UrlImage);
                _context.Agents.Remove(agent);
                if (await _context.SaveChangesAsync() > 0)
                {
                    if (System.IO.File.Exists(CurrentImage))
                    {
                        System.IO.File.Delete(CurrentImage);
                    }
                }

                return RedirectToAction("Index");
            };
            return View();

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var agent = await _context.Agents.FirstOrDefaultAsync(m => m.AgentId == id);
            return View(agent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Agent agent)
        {
            if (id != null)
            {
                if (agent.ImageUrl != null)
                {


                    agent.UrlImage = ProcessUploadImage(agent);
                    var data = await _context.Agents.FirstOrDefaultAsync(x => x.AgentId == id);
                    _context.Agents.Add(data);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                };
            }
            return View(agent);
            //var uniqueImage = ProcessUploadImage(agent);
            //var data = await _context.Agents.FirstOrDefaultAsync(x => x.AgentId == id);
            //data.ImageUrl = uniqueImage;
            //_context.Agents.Update(data);
            //await _context.SaveChangesAsync();
            //return RedirectToAction("Index");
        }
    }
}

Controllers/RouteFromController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyEticketApplication.Models;
using MyEticketApplication.Repositories.IRepository;
using MyEticketApplication.ViewModels;

namespace MyEticketApplication.Controllers
{
    public class RouteFromController : Controller
    {
        private readonly IRouteFromRepository _routeFromRepository;
        private readonly IRouteToRepository _routeToRepository;


        public RouteFromController(IRouteFromRepository routeFromRepository, IRouteToRepository routeToRepository)
        {
            _routeFromRepository = routeFromRepository;
            _routeToRepository = routeToRepository;
        }
        public IActionResult Index()
        {
            ViewBag.data = _routeFromRepository.GetAllFromRoute();

            return View();
        }
        public IActionResult Delete(int RouteFromId)
        {
            if (RouteFromId == 0)
            {
                return NotFound();
            }
            _routeFromRepository.DeleteRouteFrom(RouteFromId);
            return RedirectToAction("Index");
        }
        public IActionResult Create()
        {

            ViewData["RouteToDdl"] = _routeToRepository
         .GetRouteToInfo()
         .Select(c => new SelectListItem() { Text = c.RouteToName, Value = c.RouteToId.ToString() })
         .ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(RouteFrom routeFrom)
        {

            if (routeFrom !=null)
            {
                var data = new RouteFrom()
                {
                    RouteFromName = routeFrom.RouteFromName,
                    RouteToId = routeFrom.RouteToId,
                };
                _routeFromRepository.AddRouteFrom(data);
                return RedirectToAction("Index");

            }
            else
            {
                return View();
            }

        }

        public IActionResult Edit(int routeFromId)
        {
            var routeFrom = _routeFromRepository.GetRouteFromById(routeFromId);
            ViewData["RouteToDdl"] = _routeToRepository
         .GetRouteToInfo()
         .Select(c => new SelectListItem() { Text = c.RouteToName, Value = c.RouteToId.ToString() })
         .ToList();
            return View(routeFrom);
        }
        [HttpPost]
        public IActionResult Edit(int routeFromId,RouteFrom routeFrom)
        {
           
            if (routeFromId !=null && routeFrom !=null)
            {
                var data = new RouteFrom()
                {
                    RouteFromId = routeFromId,
                    RouteFromName = routeFrom.RouteFromName,
                    RouteToId = routeFrom.RouteToId,
                };
                _routeFromRepository.UpdateRouteFrom(data);
                return RedirectToAction("Index");
            }
            else
            {
                _routeFromRepository.GetRouteFromById(routeFromId);
                ViewData["RouteToDdl"] = _routeToRepository
             .GetRouteToInfo()
             .Select(c => new SelectListItem() { Text = c.RouteToName, Value = c.RouteToId.ToString() })
             .ToList();
                return View(routeFrom);
            }
        }
    }
}

Controllers/RouteToController.cs
using Microsoft.AspNetCore.Mvc;
using MyEticketApplication.Models;
using MyEticketApplication.Repositories.IRepository;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace MyEticketApplication.Controllers
{
    public class RouteToController : Controller
    {
        private readonly IRouteToRepository _routeToRepository;
        public RouteToController(IRouteToRepository routeToRepository)
        {
            _routeToRepository = routeToRepository;
        }

        public IActionResult Index()
        {
            var routeToInfo=_routeToRepository.GetRouteToInfo();
            return View(routeToInfo);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(RouteTo routeTo)
        {
            if (routeTo.RouteToName !=null)
            {
                _routeToRepository.AddRouteTo(routeTo);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int RouteToId)
        {
            if(RouteToId == 0)
            {
                return NotFound();
            }
                _routeToRepository.DeleteRouteTo(RouteToId);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int RouteToId)
        {
            if (RouteToId == 0)
            {
                return NotFound();
            }
            var routeTo = _routeToRepository.GetRouteToByRouteId(RouteToId);
            return View(routeTo);
        }
        [HttpPost]
        public IActionResult Edit ( RouteTo routeTo)
        {
            if (routeTo.RouteToId != null)
            {
                RouteTo data = new RouteTo()
                {
                    RouteToId = routeTo.RouteToId,
                    RouteToName = routeTo.RouteToName
                };
                _routeToRepository.UpdateRouteTo(data);
                return RedirectToAction("Index");

            }
            else
            {
                return NotFound();
            }
          
          
        }
    }
}

Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MyEticketApplicationInAspDotNetCore.Controllers
{
    [Route("[controller]")]
    public class TicketController : Controller
    {
       

        public IActionResult Index()
        {
            return View();
        }

       
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyEticketApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyEticketApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyEticketApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RouteFrom" asp-action="Index">Route From</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RouteTo" asp-action="Index">Route To</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransportInfo" asp-action="Index">Transport Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransportTypes" asp-action="Index">Transport Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agent" asp-action="Index">Agent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Admin
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Registration">Role</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                        <li class="nav-item">
                            <a class="dropdown-item" class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Registration">Registration</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            @*<li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>*@

                        }
                        else
                        {
                            @*<li class="nav-item">
                                <a asp-action="register" asp-controller="account" class="nav-link">Register</a>
                            </li>*@

                            @*<li class="nav-item">
                                <a asp-action="login" asp-controller="account" class="nav-link">Login</a>
                            </li>*@
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyEticketApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>